owncloud/QA

- Desktop_share_with_users.md
TestPlan for Desktop Client: Share with users. It contains a markdown file with the testcases for this feature
> TestPlan for Desktop Client: Share with users

- Files_external.md
Test Plan for Files External Mount Conf to DB
> TestPlan for Files External

- Mobile/iOS/Templates/528-allow_copy_paste_url_from_browser_to_login.md
> Testplan allow copy paste url from browser to login

- Mobile/Android/Templates/1209-material_buttons.md
PR dev: https://github.com/owncloud/android/pull/1209
> add test plan pr1209

- Mobile/Android/Templates/1099-switchListVSGrid.md
Dev PR: https://github.com/owncloud/android/pull/1099
> Add test plan PR 1099: switchListVSGrid

- Desktop/Smoke_test_maintenance_version.md
- Desktop/Test_Plan_Populate_account_setup_credentials_from_server_URL.md
Smoke Test maintenance version 1st version
> Smoke test maintenance version

- Server/TestPlan_WebDav_interface_WebUI.md
@PVince81 @owncloud/qa Please check if this is enough/too much.
> Added test plan for the webui webdav use

- Desktop/Regression_test_for_the_Desktop_Client.md
- Desktop/Smoke_test_maintenance_version.md
- Desktop/Test_Plan_Populate_account_setup_credentials_from_server_URL.md
Test Plan Desktop Client 1st version
> Regression test Desktop Client

- Server/TestPLan_template_system_tagging.md
@owncloud/QA @PVince81 Please review. (All enterprise options not included here).
> Added test plan template for tagging NF

- Mobile/iOS/Templates/568-share_edit_privileges.md
- Mobile/iOS/Templates/568_iOS Branding share.md
- Mobile/iOS/Templates/xxx_iOS Branding share.md
@owncloud/qa 
@owncloud/ios-developers
> added 568 branding share test plan

- Server/testplan_template_filtering_system_tags.md
Please review @PVince81, @owncloud/qa
> test plan filtering tags

- Server/Files_transfer_ownership.md
> add Files_transfer_ownership Test Plan

- Server/Test_Plan_Simplified_Smoke_Test.md
As requested by @MorrisJobke.
cc @owncloud/qa
> Added simple smoke test plan

- Server/Test_Plan_Federated_Sharing.md
Brought S3 spreadsheet tests here, with some changes. @owncloud/QA
> Added test plan for federated sharing

- Server/Test_Plan_Sharees.md
In Sharee Test Plan, add test cases related to LDAP offline as it was requested in https://github.com/owncloud/QA/issues/173
Please 👀 @owncloud/qa @PVince81 @blizzz
> add test cases related to LDAP offline

- Server/Pluggable_Auth_Test_Plan.md
Add Pluggable Auth TestPlan to QA repository
@owncloud/qa @ChristophWurst
> Pluggable auth TestPlan

- Mobile/iOS/Templates/Release_3.5.0/690-change_synced_icons.md
cc @owncloud/ios-developers @owncloud/qa-team
> Add test plan PR 690: Sync icons update + available offline wording

- Mobile/Android/Templates/Release_2.1.0/1709_show_displayname_instead_of_username.md
> Add test plan PR 1709: Show display name instead of user name

- Mobile/iOS/Templates/Release_3.5.0/702_video_upload_fix.md
cc @Jon-Schneider @owncloud/ios-developers
> Add test plan  PR 702: Video upload fix

- Desktop/Regression_test_for_the_Desktop_Client.md
After noticing some typos, I started reviewing this document. Then there
were so many things to change that I wondered if this is actually a
document that is being used anyway, or is it something that someone
started a while ago and it has never been finalized?
So let me know what is the status of the documents in this QA repo.
> Various typos

- Mobile/Android/Templates/Release_2.1.0/1599-resized_images.md
cc @tobiasKaminsky @owncloud/android-developers
> Add test plan PR 1599: Resized images

- Mobile/Android/Templates/Release_2.1.0/1368-document_provider.md
> Add test plan PR 1368: Document provider

- Mobile/Android/Templates/Release_2.1.0/1176-multiselect.md
> Add test plan PR 1176: Multiselect

- Mobile/iOS/Templates/Release_3.5.0/709-text-editor.md
- Mobile/iOS/Templates/Release_3.5.0/xxx-text-editor.md
> Add test plan PR 709: Text editor

- Desktop/v2.2.0/590-branding_share.md
Hi hi:
New test plan for branding internal share.
@owncloud/qa 
Regards
> 590 branding share

- Desktop/v2.2.0/Internal_Share_Enhancement_Template.md
Hi Hi:
I´ve created this test plan just for:
https://github.com/owncloud/client/issues/4383
https://github.com/owncloud/client/issues/4679
@owncloud/qa @ckamm
> Internal Share Enhancement Test Plan

- Mobile/Android/Templates/Release_2.1.0/xxx-update_downloaded_files.md
> Add test plan PR 1736: Update changes on downloaded files

- Server/Updater_TestPlan.md
Add template for Updater Testplan feature to the QA repo
@VicDeo @jvillafanez
> Add Updater TestPlan

- Mobile/Android/Templates/Release_2.1.0/1698-available_offline_folders.md
> Add test plan PR 1698: Availble offline folders

- Mobile/Android/Templates/Release_2.1.0/1752-share-option-federated-9.1.md
> Add test plan PR 1752: Share option in federated shares v9.1

- Mobile/Android/Templates/Release_2.1.0/1749-customizable_strings_search_provider.md
> Add test plan PR 1749: Customizable strings search provider

- Desktop/Fixed_server_URL_with_branded_client_update.md
Fixed_server_URL_with_branded_client_update Test plan
Please review @owncloud/qa @ogoffart @rperezb
> server_url_updated Test 

- Mobile/Android/Templates/Release_2.2.0/1655-folderSize.md
> Add test plan PR 1655: Folder Size & Sort by Size

- Mobile/Android/Templates/Release_2.2.0/xxx_instant_uploads_based_observer.md
> Add test plan PR xxx: Instant upload from observer

- Mobile/Android/Templates/Release_2.2.0/1813-edit_options_federated_9.1.md
> Add test plan pr 1813: Edit options in federated share

- Mobile/Android/Templates/Release_2.2.0/1812-reorder_menu_options.md
> Add test plan PR 1812: Reorder menu items

- Mobile/Android/Templates/Release_2.2.0/136lib-chunk_assembling-big-files.md
cc @jabarros @owncloud/android-developers
> Add test plan PR 136lib: Chunk assembling in big files

- Mobile/Android/Templates/Release_2.2.0/1814-internal_music_player_stop.md
cc @jabarros @owncloud/android-developers
> Add test plan PR 1814: Internal music player does not stop if file is removed

- Mobile/iOS/Templates/Release_3.5.2/774-clear_uploads_list.md
cc @nasli @guruz @owncloud/ios-developers
> Add test plan PR 774: Clear upload list

- Mobile/iOS/Templates/Release_3.5.2/783-parent_folder_instead_of_back.md
> Add test plan PR 783: Show parent folder instead of "Back" (if room)

- Mobile/iOS/Templates/Release_3.5.2/782-separate_videos_photos_instant_uploads.md
cc @owncloud/ios-developers @Jon-Schneider
> Add test plan PR 782: Separate videos and photos instant uploads

- Mobile/Android/Templates/Release_2.2.0/1556-new_drawer_accouns_settings.md
cc @AndyScherzinger @owncloud/android-developers
> Add test plan PR 1556: New drawer, Accounts manager and Toolbar

- Mobile/iOS/Templates/Release_3.5.2/814-update_useragent.md
> Add test plan pr 814: Update user agent

- Mobile/iOS/Templates/Release_3.5.3/xxx-maintenance_mode.md
> [PR 821] Add test plan maintenance mode

- Mobile/Android/Templates/Release_2.3.0/1869_encoding_password_share_link.md
CC @owncloud/android-developers
> Add test plan PR 1869: Encoding passwords of share links

- Mobile/Android/Templates/Release_2.3.0/1880_specific_error_share.md
> Add test plan PR 1880: Clearer error in share if not supported

- Mobile/iOS/Templates/Release_3.5.2/xxx-url_server_changes.md
> Add test plan: URL changed

- Mobile/iOS/Templates/Release_3.5.3/xxxx_user_quota_error.md
> Add test plan PR ... : User quota

- Mobile/Android/Templates/Release_2.3.0/1881_improve_feedback_errors.md
> Add test plan PR 1881: Improve error feedback 

- Mobile/Android/Templates/Release_2.3.0/1886_user_quota_error.md
> Add test plan pr 1886: error insufficient qouta

- Mobile/Android/Templates/Release_2.3.0/1891_fix_login_oc10.md
> Add test plan PR 1891: Fix login in oC 10

- Mobile/Android/Templates/Release_2.3.0/1895_firewall_error_messages.md
> Add test plan PR 1895: Firewall error messages

- Mobile/Android/Templates/Release_2.3.0/1908-privacy_policy.md
> Add test plan PR 1908: Privacy Policy

- Mobile/iOS/Templates/Release_3.5.4/xxx-fix_saml_files_av_offline.md
> Add test plan PR xxx: Fix - av. offline files in SAML freezes

- Mobile/iOS/Templates/Release_3.5.4/854-officefileview.md
> Add test plan PR 854: Office view

- Mobile/Android/Templates/Release_2.4.0/1921-uppercase_url.md
> Add test plan PR 1921: Uppercase in URL

- Mobile/Android/Templates/Release_2.4.0/1927-doze_adapt.md
@davigonz do you miss anything in the tc?
> Add test plan PR 1927: Adapt to Doze & App Standby

- Server/Test_Plan_Settings.md
A test plan to be passed after required PRs are merged:
https://github.com/owncloud/core/pull/26449
https://github.com/owncloud/core/pull/26759
**After** because it was agreed (mattermost, server channel) that PRs should be merged and start to move on while expecting bugs to be raised.
> Added test plan for the new settings section

- Server/Test_Plan_External_Auth.md
table is messed up in Server/Test_Plan_External_Auth.md
this fixes the formatting
> fix the table

- Mobile/Android/Templates/Release_2.5.0/1978-permalink.md
- Mobile/iOS/Templates/Release_3.6.1/899-2FA_passcode.md
> Add test plan PR 1978: Permalink

- Mobile/iOS/Templates/Release_3.7.0/904-permalink.md
> Add test plan PR 904: Private Link

- Mobile/Android/Templates/Release_2.5.0/1984-antivirus_error_message.md
> Add test plan [PR 1984]: Improve antivirus error message

- Mobile/Android/Templates/Release_2.5.0/1988-write_only_public_shares.md
> Add test plan PR 1988: Write-only public shares

- Mobile/Android/Beta Program/Beta_test.md
> Add test plan Beta program

- Mobile/iOS/Templates/Release_3.6.2/913-write-only-shares.md
> Add test plan PR 913: Write-only shares

- Server/TestPLan_addressbook.md
Besides I am testing it already, better to have the test plan template ready.
Please review,
@owncloud/qa @DeepDiver1975 .
> Added test plan for addressbook.

- Server/GuestAppTestPlan.md
Add  template for Guests feature  Test Plan. Feel free to comment!
> Add Guests Test Plan

- Desktop/OAuth2_support.md
and various little words here and there, while I am looking at what PRs are waiting in QA.
> Add Edge to Oauth2 test plan

- Server/Test_Plan_Diagnostics.md
There is something which is more a concern than a test case, but I see that the log file can get really heavy. The app should warn the user if the size of the file is too big as this can cause problems to the server. Or at least recommend a setup which removes these logs often, perhaps after storing them somewhere.
> Test plan for diagnostics app

- Mobile/Android/Templates/Release_2.5.0/2019-forbidden_reshare.md
> Add test plan PR 2019: Forbidden reshare

- Server/Test_Plan_Activity.md
add Test Plan for Activity app. Feel free to comment!
> add Test Plan for Activity app

- Server/Test_Plan_Files_Antivirus.md
> testplan for files antivirus

- Server/Test_Plan_Files_Antivirus.md
as we have the `$user` variable we can use them more in the upload examples
> use $user consequent in upload examples

- Server/Test_Plan_Simplified_Smoke_Test.md
just a small PR to mark the tests that are already run by automated UI tests
> mark automated tests with gear symbol

- Server/Test_plan_Files_Texteditor
- Server/Test_plan_Files_Texteditor.md
This app had no test plan template. So this is it - which is a basic overview of what the automated UI tests do.
> Test Plan Template for files_texteditor

- Server/Test_Plan_Simplified_Smoke_Test.md
some more tests marked as automated
> mark automated tests as such

- Server/Test_Plan_Pluggable_Auth.md
- Server/Test_Plan_Sharees.md
Issue #479 
The old version was only mentioned in 2 places.
> Update Ubuntu version to 16.04

- Mobile/Android/Templates/Release_2.5.1/2038-Privatelink_from_dav.md
> Add test plan [PR 2038]: Private link from DAV proerty

- Server/Test_Plan_Simplified_Smoke_Test.md
Automated by PR https://github.com/owncloud/core/pull/29521
> Public Link Share tests are automated

- Server/Test_Plan_Simplified_Smoke_Test.md
Automated by PR https://github.com/owncloud/core/pull/29573
> File upload tests are automated

- Server/Test_Plan_Simplified_Smoke_Test.md
Automated by PR https://github.com/owncloud/core/pull/29097
Note: need to review the item 2 lines down from this change also and make the automated tests do all combinations mentioned there. Now that we have upload as well as federation sharing tests, we should be able to do combinations.
> Federated Sharing is automated

- Server/Test_Plan_Simplified_Smoke_Test.md
PR master https://github.com/owncloud/core/pull/29636
PR stable10 https://github.com/owncloud/core/pull/29641
> Share with user and groups smoke test automated

- Mobile/Android/Templates/Release_2.5.1/2062-Autouploads.md
> Add test plan PR 2062: New instant uploads (camera uploads)

- Server/Test_Plan_Files_Antivirus.md
just a couple of loops to be able to work through the tests quicker
> some small scripts to test quicker

- Server/Test_Plan_twofactor_totp.md
Removed test case about shibboleth.
> twofactor_totp cannot work with shibboleth

- Mobile/iOS/Templates/Release_3.7.3/1015-files_preview.md
> Add test plan PR 1015: Files prefiew

- Mobile/iOS/Templates/Release_3.7.3/1020-fix_migration.md
> Add test plan PR 1020: Fix migration

- Mobile/iOS/Templates/Release_3.8.0/999-open_link_in_app.md
> Add test plan PR 999: Open link within the app

- Mobile/iOS/Templates/Release_3.7.3/1021-fix_upgrading.md
> Add test plan PR 1021:  Fix upgrading

- Mobile/Android/Templates/Release_2.7.0/1375-welcome_wizard.md
> Add test plan PR 1375: Welcome wizard

- Mobile/Android/Templates/Release_2.7.0/2128-fingerprint_lock.md
> Add test plan PR 2128: Fingerprint lock

- Server/Test_Plan_OAuth2.md
closes #485 
Requires a "_Integration with other apps_" section. -> https://github.com/owncloud/oauth2/issues/113
> OAuth2 server app testplan

- Mobile/Android/Templates/Release_2.8.0/2134-sort_descending.md
> Add test plan PR 2134: Sort descending android 

- Mobile/Android/Templates/Release_2.8.0/2175-manage_accounts_deleted_account.md
> Add test plan PR 2175: unblock deleted account

- Mobile/Android/Templates/Release_2.8.0/2150-new_look_public_link.md
> Add test plan PR 2150:  Look of permission public links

- Mobile/iOS/Release_3.8.0/1046-update_.web_api.md
@pablocarmu @nasli do you miss any case?
> Add test plan PR 1046: Update web API

- Server/Test_Plan_OAuth2.md
mark tests that were automated in the oauth app as such see https://github.com/owncloud/oauth2/tree/master/tests/acceptance/features/webUIOauth2
> mark oauth tests as automated

- Mobile/Android/Templates/Release_2.8.0/2214-user_quota.md
> Add test plan PR 2214: User qouta 

- Server/Test_Plan_files_pdfviewer.md
New Test Plan for Files PDF Viewer app
> add Test_Plan_files_pdfviewer

- Mobile/Android/Templates/Release_2.9.0/2274-local_search.md
> add test plan PR 2274: Local search

- Server/Test_Plan_Smoke_Test.md
Add new scenarios to the Smoke Test
> update Smoke Tests

- Server/Test_Plan_Smoke_Test.md
add Two Factor Authentication to scenarios to be tested in the Smoke test in order to cover all login methods.
> add Two Factor Authentication to scenarios

- Mobile/Android/Templates/Release_2.9.0/2308-jobs_for_available_offline.md
First drafts for test plan
@davigonz
> Add test plan PR 2306: Av. offline jobs

- Server/Test_Plan_Firstrunwizard.md
Create testplan for `firstrunwizard` app
Related issue https://github.com/owncloud/firstrunwizard/issues/97
> Add test plan for First run wizard 1.2.0 

- Server/Test_Plan_External.md
Create testplan for `external` app
Related issue https://github.com/owncloud/external/issues/12
> Add test plan for External 1.4.0RC1

- Desktop/Test Plan Password policy.md
Password Policy 2.0.0 app was published with GPLv2 license on Jul. 17th 2018. We should publish the `Test Plan Password policy.md` in the public QA repo as well…
More information:
https://marketplace.owncloud.com/apps/password_policy
> publish Test Plan Password policy.md

- Server/Test_Plan_Files_Mediaviewer.md
This PR adds few test scenarios for the `files_mediaviewer`.
> Adjust test plans for files_mediaviewer

- Server/Test_Plan_Full_search.md
> add Test Plan Full Search

- tools/hetzner_deployment/make_machine.py
- tools/hetzner_deployment/scripts/test_script.py
neue Datei:     tools/hetzner_deployment/scripts/test_script.py
> 	geändert:       tools/hetzner_deployment/make_machine.py

- Server/Test_Plan_Activity.md
As there is no favorite activity mechanism implemented
> Remove favorite section from activity testplan

- Desktop/Regression_Test_Plan_Minor_Release.md
Testplan Release Desktop 2.9 https://github.com/owncloud/client/issues/8870
> apply changes from 2.9 testplan ticket

- Desktop/Regression_Test_Plan_Patch_Release.md
https://github.com/owncloud/client/issues/9079
> Apply improvements from 2.9.1 Release

- Desktop/Regression_Test_Plan_Minor_Release.md
For those tests that are already automated we:
- Added 🤖 sign on the `testID` column
- Added ✔️ on the `Result` column
- Added feature files containing the respective test on `Related Comments` column
Update from https://github.com/owncloud/client/issues/8971
> Updated Regression_Test_Plan_Minor_Release that are already automated

- Server/Test_Plan_Files_Texteditor.md
> files_texteditor testplan update

- Desktop/Regression_Test_Plan_Patch_Release.md
https://github.com/owncloud/client/issues/9488#issuecomment-1060711521
> Apply improvements from 2.10.1 release

- Server/Test_Plan_OCIS_Smoke_Test.md
This `OCIS_somke_test_plan` is documented with `test via API`. Just need a confirmation whether to test it via API or doing it via manaul testing?
> Refactor OCIS smoke test plan

- Server/Test_Plan_OCIS_Smoke_Test.md
- After admin shares file to Marie with viewer role, Marie cannot copy file but can share and copy quicklink
> updated oCIS_Smoke_Test of Case 2

- Server/Test_Plan_OCIS_Smoke_Test.md
When `Kathrine` sharing space with `marie` with role editor, actually `marie` can create resource inside space and share the resource inside of space.
> Refactor OCIS_Smoke_test_plan for createing resource inside space

- Desktop/OAuth2_support.md
> org with com replaced

- Server/Test_Plan_OCIS_Compatibility_Test.md
The compatibility test was out of date. updated it
> update compatibility checklist

- Server/Test_Plan_OCIS_Smoke_Test.md
1. Sharer of a folder will be the owner of resource uploaded/created inside that folder so sharee should not be able to see the version history:
- Marie cannot see version history for `case1`
2. Functions of `space manager`:
- Added another user "Moss" with `manager` role and listed his abilities and inabilities for `Case5: space story`
> Refactor OCIS_Smoke_test_plan
